name: Update Tournament Tables

on:
  schedule:
    # Запуск каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch: # Включает кнопку ручного запуска в интерфейсе

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        run: node index.js
